# Generated by Django 5.0.7 on 2024-07-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
